### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by djherbis** [FourSee/ShellGame#1]
Hey, I'm happy to see you use djherbis/stream, but is there any reason you chose it over just doing:

```go
buf := bufio.NewReader(os.Stdin)
r := buf
if !silent {
  r = io.TeeReader(buf, os.Stdout)
}
send(r, 0, "")
```

For [this code](https://github.com/FourSee/PolyRhythm-Agent/blob/master/stdinMessage.go#L25)

**Comment by stevenallen05** [comment]
Mostly because I was attempting an experiment with catching exit codes at stdin EOF, but those were a complete failure. I decided to check this in before I made an even bigger mess, even in its horrific current state.

**Comment by djherbis** [comment]
Sure that sounds reasonable, if you ever have questions about djherbis/stream I'm happy to help.

Have a great weekend.
